kevquirk/simple.css

simple.css

The name of the system font on MacOs is actually `-apple-system`. See also: https://css-tricks.com/snippets/css/system-font-stack/

Fix name of `-apple-system`

---

simple.css

As mentioned in the other PR, this update fixes capitalisation of the fonts (and adds `Menlo`, which ships with MacOS by default, and is objectively less ugly than `Monaco`. ;-) )

Updating Font stack

---

simple.css

Hi, 
This PR updates the typography of headings. What I've done is changing the scaling and spacing to variables, and made it a bit more consistent and balanced (imho, obviously). 
It's also easier to change these values this way, for people using SimpleCSS. 
Here's a screenshot of "before" and "after":

Updating Header typography

---

simple.css

I've changed these four HTML tags a tiny bit. A monospaced font is optically larger at the same point size, because on average the letters are much wider. This PR compensates that by making monospaced tags slightly smaller. 
After:
Before: 
I've noticed the indentation of the CSS is all over the place if you're not using an IDE that 'hides' that from you: '2 spaces', '4 spaces' and '1 tab' are used together. After this one is merged in, I'd like to make a PR to fix the formatting, if that's OK with you. It'll be a large delta, without functional changes.

Updating `kbd`, `mark`, `code` and `pre`

---

package.json

Simple.css is now on NPM: https://www.npmjs.com/package/simpledotcss
Unfortunately the original name was too similar to another package name so I published it as simpledotcss. This PR updates package.json to fit this.

Update package.json to match npm name 

---

simple.css

Simple.css had disabled the browser default style for checkbox and radio, but did not implement its own, which resulted in all checkboxes and radio buttons looking always unchecked. Created a simple checkboxes and radio buttons using just css.
Also added a little arrow to <select> to make it obvious that it is a drop-down selection.
And fixed disabled states for checkbox, radio button and <select>.

Fixed checkboxes, radio buttons and drop-down selection

---

simple.css

Just noticed this a couple times when I copy/paste the non-minified version.

Semi-colon missing in `table`

---

simple.css

**Summary**
This PR fixes the inconsistent use of spaces and tabs in the main CSS file.
**Description**
It appears some lines use 2 spaces, some use a tab and others still use both 2 spaces followed by a tab. While this does not impact the minified version, the non-minified version will IMHO improve by using a consistent indentation.
Given that the majority of lines use an indentation of 2 spaces, I chose this as the convention. I'll leave it at @kevquirk 's discretion to overrule the chosen convention and, upon doing so, I'll update the PR.
**Additional measures**
To prevent future PRs from messing up the indentation, one could add automation rules with packages like [prettier](https://www.npmjs.com/package/prettier) to either check indentation at committing and refuse if the changes do …

Fix inconsistent use of spaces and tabs

---

simple.css

Header content takes `100vw` leaving no space for `padding: 2rem .5rem;` that causes header overflow and horizontal scrollbar on mobile devices. Changing to `box-sizing: border-box;` makes content+padding fit the viewport width instead of just the content.

Header padding overflows viewport

---

simple.css

Chrome console say : 'appearance' should be listed after '-webkit-appearance'.
with this link for more information : 
https://webhint.io/docs/user-guide/hints/hint-css-prefix-order/?source=devtools

'appearance' should be listed after '-webkit-appearance'.

---

simple.css

When `details` is closed, the padding on this element makes the box larger than the tap target, since you can only click on `summary` itself. By moving the padding to `summary` when `details` is collapsed, the tap target takes up the entire visual box. Then it can be moved back to `details` when expanded to keep padding around the contents.
**Before:**
(blue above is the tap target, so clicking on the padded area of `details` does nothing, even though there's no visual distinction)
**After:**
{entire box is now a tap target, with padding applied to `summary` element when collapsed)
I suppose it's also possible to use `padding: unset` or similar for `details[open]` if you wanted to keep it more general than `padding: 0;`. Also there are other ways to handle this in terms of CSS attribute …

Move padding to `summary` for larger tap target

---

simple.css

This pull request fixes linting consistency in `simple.css`. The file was auto fixed using [prettier](https://prettier.io/) and  [stylelint](https://stylelint.io/).
- Adds missing closing semicolon
- Prefer single quotes over double quotes
- Keep line length under 80
- Prefer lower case for hex colors
- Prefer new line for multiple selectors 
- Include leading 0 in decimal values
A GitHub action could also be setup to prevent linting errors from being introduced in the future.

Fix `simple.css` linting errors

---

simple.css

The `nav` items will have a margin applied to them to adjust for spacing, but fail to clear the margin on the last item, pushing a wide menu off by ~1em.
This removes it.

Add fix for last-child items in a `nav`

---

simple.css

The `kbd` element produces really thin 'keys'. Keys look better when the left and right padding is increased just a little.

Increase left and right padding for 'kbd' element

---

simple.css

Just some more simple fixes. Found mostly by my editor:
* Disabled elements: remove `cursor: default` as the property `cursor: not-allowed` is defined right after it.
* `pre` blocks had `overflow: auto` and `overflow-x: auto`. Only one is needed. I erred on the side of caution and chose the more encompassing option.
Most of these were presenting as expected, so no visual changes, however bytes are bytes. Especially when they're duplicate bytes.

Remove duplicate properties

---

simple.css

This change would allow for navigational elements to house ordered and unordered lists, while adhering to the look-and-feel of the 'traditional' navigation of `nav > a + a + a ...`.

Navigation list items

---

simple.css

Tables need to have overflow and displays set in order to prevent the tr tags from forcing expansion.
Here're before and after shots:
I believe this is the most clean solution.

Fixes Table Overflow

---

simple.css

It looks better with middle 😄
before: 
after:
Also does work with normal characters.

Change "radio" to `vertical-align: middle`

---

simple.css

Thank you for an awesome project - was a great starting point for some dev I was doing 
This PR adds the following:
- add dark scrollbar for dark theme
- consistent hovering (brightness is applied to navbar hovering)
- style progress bar
(Adapted from changes for some webdev I was doing - https://fhpwa.github.io/. There were some other changes made around theming but I've held off as I'm not sure if that diverges too much from the theming this project aims to do. On the off-chance it would be useful happy to contribute further)
Hope this is useful, any tweaks etc - please let me know

Style Progress Bar and a few minor tweaks 

---

index.html
simple.css

Current section boundary behavior is awkward and not in the testing page. This PR fixes that.
- Adds sections to the test page
- Modifies section boundary behavior
- Sections at the start of a container have no top boundary
- Sections at the end of a container have no bottom boundary
- Sections next to each other only share one border
- Ensures sections still exhibit old behavior when placed inline with non-sectioned HTML
- Resolves #105

Section boundaries

---

simple.css

Instead of changing the padding on `summary`, it's good to change the padding directly on `details` to reduce the code, it has the same effect.
Using `background` (shorthand) just for color it's really not a good practice, since it will add the rest of  `background` property **by default** with the value such as `background-attachment`, `background-clip`, `background-origin`, `background-repeat`, `background-size`.

Improve details and change background to background-color

---

simple.css

Bottom margin on summary of open details should only be applied to the summary that is a direct child, not to more deeply nested summary tags that might not be open. 
Otherwise, nested details tags will look weird when they are not open, because the bottom margin of the summary would be larger than the top margin.

Fix summary margins when using nested details

---

index.html
simple.css

Added a change because the dt column in a document list ends up taking most of the space, instead of taking up half the space. This happened when I added word-break and overflow-wrap to one of the dd elements. The dt column then took more than half of the available space and forced a word-break even though there was enough space.
Or maybe write `grid-template-columns: auto` also seems to work.
If u want more info, I'm happy to share.
- Denis

Change dl grid-template-columns

---

index.html
simple.css

Currently there is very little space between the `<hr>` and the preceding and succeeding paragraphs. This adds a bit more margin to improve aesthetics.
Closes #115

Update hr vertical margin from 1rem to 3rem

---

simple.css

In the [MDN Docs for abbr](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr?retiredLocale=de) the title attribute is not always present and it is recommended to explain the abbreviation in plain text the first time the abbreviation is used. 
Considering this I think it makes little sense to change the cursor on hover because this could lead to confusion as nothing happens upon hovering. Whenever there is a title attribute then changing the cursor makes sense. To make the abbreviation stand out from normal text I think some form of styling is also welcome to communicate interactivity to the user.
A different styling would be to add content like `(?)` after it, but I think this doesn't speak to the simpleCSS design principle and the dotted underline also seems to match what …

Change abbr css

---

simple.css

With `display: block`, a table doesn't stretch to the whole box. CSS `width` property is completely ignored if it's a `block`.

Fix table ignoring width

---

simple.css

Buttons appear not to use the `html` font setting. ¯\_(ツ)_/¯

Ensure buttons inherit font

---

simple.css

👋🏼  I noticed `sup` and `sub` tags were (very) subtly affecting line-heights and added a fix ([credit](https://css-tricks.com/snippets/css/prevent-superscripts-and-subscripts-from-affecting-line-height/)).
| Before | After  |
| ------ | ------ |
| <img width="812" alt="Screenshot 2023-06-21 at 9 36 45 PM" src="https://github.com/kevquirk/simple.css/assets/4173104/f0c71046-02d5-4731-8a75-2942a77e0090"> | <img width="812" alt="Screenshot 2023-06-21 at 9 36 30 PM" src="https://github.com/kevquirk/simple.css/assets/4173104/6eb66e86-3540-4831-8554-5bc1a00ddeb3"> |

Preventing sup/sub from affecting line-height

---

.github/workflows/npm-publish.yml

Requires the NPM token to be a secret with the key "NPM_TOKEN".

Add NPM publish workflow. Fixes #150

---

simple.css

When you add an `input[type=text]` next to an `input[type=submit]`, they are not aligned vertically.
This PR uses the same styles for inputs and buttons to fix this.
Before: 
After: 
I tested this PR with Firefox on Windows.

Same styles for buttons and inputs

---

simple.css

Fixes margin collapse for adjacent sections. I used a separate `section+section` selector because I don't think `section:first-child` should have no top margin.
Also collapse the margin h3 tags at the start of a section or article. There was already an equivalent rule for h2 so it looked to me like it was forgotten.

fix (missing) margin collapses for sections

---

simple.css

I’m building a site with Simple.css and I have a Blog link in the header. From there I have a list of blog posts in the body. If someone clicks on an individual blog article, I'd still like to highlight "Blog" as it’s the current section. But it isn’t the current page. Best I can see from a bit of searching, the way to mark this up is to use `aria-current="true"`. This indicates Blog as being the current item in a set, without declaring that it’s the current page.
My suggestion is to add support for `aria-current="true"`. That’s helpful for more general applications of `aria-current`. That said, if there’s a better way to indicate "current section" I'm all ears.

Aria current tweak

---

simple.css

Fixes #214 
Using variables specified in `:root` still works, because `::backdrop` inherits from `<dialog>` which inherits from `:root`.
Also fixed an issue in Firefox where the background of a dialog element would be gray instead of white in light mode.

Remove unnecessary ::backdrop selector from :root 

---

index.html
simple.css

Added a variable to control border width and updated every element with a 1px border size to use the variable instead, as well as `hr` height and the `.notice` class. The `.notice` class previously had a border width of 2px.
Also added the `.notice` class to the test page under a new "Classes" section.
Fixes #236

Add --border-width variable

---

simple.css

Wide figures would have their caption go out of view otherwise.
By the way, thanks for the good laugh I had reading the actual contents of the example table! 😀

Keep figure captions on the screen while scrolling

---

simple.css

Hello, I always find it useful.
Thank you for the wonderful CSS library.
I noticed that when I tried to change the size of the radio button slightly, the check mark was misaligned.
I think this is not a common scenario, but it may work if you set the size of the radio button to a relative value.
If you were to write it in index.html, it would be the following sample code,
but I didn't include it in the commit because I didn't want to put a style tag in a simple test page.
```html
<p>Nested <code>label > input with custom font-size</code></p>
<ul style="font-size: 2rem; line-height: 2;">
<li><label for="radio7"><input id="radio7" name="radio" type="radio" checked="checked">
Option 1</label></li>
<li><label for="radio8"><input id="radio8" name="radio" type="radio"> Option 2</label></li> …
```

Change radio:checked::after size to relative value (to 2em from 32px)
